name: Clean Clash Sub
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run_clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install python dependencies
        run: |
          python3 -m pip install pyyaml

      - name: Download source clash.yaml
        run: |
          curl -L -o source.yaml "https://github.com/Au1rxx/free-vpn-subscriptions/raw/main/output/clash.yaml"

      - name: Run clean script
        run: python3 clean.py

      - name: Commit & push cleaned file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add clash_fixed.yaml
          git commit -m "auto update cleaned sub" || echo "no changes"
          git push
